name: eventnerf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - absl-py=1.0.0=pyhd8ed1ab_0
  - aiohttp=3.8.1=py39h3811e60_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - aom=3.2.0=h9c3ff4c_2
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=21.1.0=py39h3811e60_2
  - async-timeout=4.0.1=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - blosc=1.21.0=h9c3ff4c_0
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py39h3811e60_1003
  - brunsli=0.1=he1b5a44_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - c-blosc2=2.0.4=h5f21a17_1
  - ca-certificates=2022.5.18.1=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - cairo=1.16.0=h6cf1ce9_1008
  - certifi=2022.5.18.1=py39hf3d152e_0
  - cffi=1.15.0=py39h4bc2ebd_0
  - cfitsio=4.0.0=h9a35b8e_0
  - charls=2.2.0=h9c3ff4c_0
  - charset-normalizer=2.0.8=pyhd8ed1ab_0
  - click=8.0.3=py39hf3d152e_1
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - conda=4.11.0=py39hf3d152e_0
  - conda-package-handling=1.7.3=py39h3811e60_1
  - configargparse=1.5.3=pyhd8ed1ab_0
  - cryptography=36.0.0=py39h95dcef6_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudatoolkit-dev=11.4.0=h5e8e339_5
  - cycler=0.11.0=pyhd8ed1ab_0
  - cytoolz=0.11.2=py39h3811e60_1
  - dask-core=2021.11.2=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=py39hde42818_1002
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.4.1=h6987444_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.2=py39h3811e60_0
  - freeglut=3.2.1=h9c3ff4c_2
  - freetype=2.11.0=h70c0345_0
  - frozenlist=1.2.0=py39h3811e60_1
  - fsspec=2021.11.1=pyhd8ed1ab_0
  - fzf=0.28.0=ha8f183a_0
  - gettext=0.21.0=hf68c758_0
  - giflib=5.2.1=h516909a_2
  - glib=2.70.1=h780b84a_0
  - glib-tools=2.70.1=h780b84a_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.15=he1e5248_0
  - google-auth=2.3.3=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - graphite2=1.3.14=h23475e2_0
  - grpcio=1.42.0=py39hff7568b_0
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - h5py=3.6.0=nompi_py39h7e08c79_100
  - harfbuzz=3.1.1=h83ec7ef_0
  - hdf5=1.12.1=nompi_h2750804_102
  - icu=68.2=h9c3ff4c_0
  - idna=3.2=pyhd3eb1b0_0
  - imagecodecs=2021.11.20=py39h571908b_1
  - imageio=2.9.0=py_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.5.0=py39hef51801_1
  - ipython=7.30.0=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jasper=2.0.33=ha77e612_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39hf3d152e_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9d=h516909a_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hf3d152e_7
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_1
  - jupyter_core=4.9.1=py39hf3d152e_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - jxrlib=1.1=h516909a_2
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - lame=3.100=h14c3975_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libaec=1.0.6=h9c3ff4c_0
  - libarchive=3.5.2=hccf745f_1
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libdrm=2.4.109=h7f98852_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=11.2.0=h69a702a_11
  - libgfortran5=11.2.0=h5c6108e_11
  - libglib=2.70.1=h174f98d_0
  - libglu=9.0.0=he1b5a44_1001
  - libgomp=11.2.0=h1d223b6_11
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f98852_0
  - liblapack=3.9.0=12_linux64_mkl
  - liblapacke=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libmamba=0.18.2=h3985d26_0
  - libmambapy=0.18.2=py39h8bfa403_0
  - libnghttp2=1.46.0=hce63b2e_0
  - libogg=1.3.5=h27cfd23_1
  - libopencv=4.5.3=py39ha7f30a5_5
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.16=h516909a_0
  - libpng=1.6.37=hed695b0_2
  - libpq=13.5=hd57d9b9_0
  - libprotobuf=3.18.1=h780b84a_0
  - libsodium=1.0.18=h516909a_1
  - libsolv=0.7.19=h780b84a_5
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.18.0=h7f98852_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libuv=1.42.0=h7f98852_0
  - libva=2.13.0=h7f98852_0
  - libvorbis=1.3.7=he1b5a44_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.14=h7b6447c_0
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - libzopfli=1.0.3=he1b5a44_0
  - llvmlite=0.38.1=py39h7d9a04d_0
  - locket=0.2.1=py39h06a4308_1
  - lpips=0.1.3=pyhd8ed1ab_0
  - lz4-c=1.9.3=h9c3ff4c_1
  - lzo=2.10=h516909a_1000
  - mamba=0.18.2=py39hfa8f2c8_0
  - markdown=3.3.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib=3.5.0=py39hf3d152e_0
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mesalib=18.3.1=h590aaf7_0
  - mistune=0.8.4=py39h3811e60_1005
  - mkl=2021.4.0=h06a4308_640
  - multidict=5.2.0=py39h3811e60_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.27=ha770c72_1
  - mysql-libs=8.0.27=hfa10184_1
  - nbclient=0.5.9=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hf3d152e_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.6.3=pyhd8ed1ab_1
  - notebook=6.4.6=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.72=hb5efdd6_0
  - numba=0.55.1=py39h66db6d7_1
  - numpy=1.21.4=py39hdbf815f_0
  - oauthlib=3.1.1=pyhd8ed1ab_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.3=py39hf3d152e_5
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1o=h166bdaf_0
  - opt-einsum=3.0.0=py_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39hde0f152_1
  - pandoc=2.16.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py39hde42818_1002
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.5.2=pyhd8ed1ab_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - prompt_toolkit=3.0.22=hd8ed1ab_0
  - protobuf=3.18.1=py39he80948d_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-opencv=4.5.3=py39hef51801_5
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.8=py_0
  - pybind11-abi=4=hd8ed1ab_3
  - pycosat=0.6.3=py39h3811e60_1009
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyjwt=2.0.1=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pyrsistent=0.18.0=py39h3811e60_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pywavelets=1.2.0=py39hce5d2b2_0
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h37b5a0c_1
  - qt=5.12.9=hda022c4_4
  - qtconsole=5.2.1=pyhd8ed1ab_0
  - qtpy=1.11.2=pyhd8ed1ab_0
  - readline=8.1=h46c0cb4_0
  - reproc=14.2.3=h7f98852_0
  - reproc-cpp=14.2.3=h9c3ff4c_0
  - requests=2.26.0=pyhd8ed1ab_1
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.8=pyhd8ed1ab_0
  - ruamel_yaml=0.15.80=py39h3811e60_1006
  - scikit-image=0.18.3=py39hde0f152_0
  - scipy=1.7.3=py39hee8e79c_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=59.2.0=py39hf3d152e_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.8=he1b5a44_3
  - sqlite=3.36.0=h9cd32fc_2
  - svt-av1=0.8.7=h9c3ff4c_1
  - tensorboard=2.7.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.6.0=py39h95dcef6_1
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorboardx=2.4=pyhd8ed1ab_0
  - termcolor=1.1.0=py_2
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - tifffile=2021.11.2=pyhd8ed1ab_0
  - tk=8.6.11=h27826a3_1
  - toolz=0.11.2=pyhd8ed1ab_0
  - torchvision=0.11.1=py39_cu113
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - trimesh=3.9.35=pyh6c4a22f_0
  - typing-extensions=4.0.0=hd8ed1ab_0
  - typing_extensions=4.0.0=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - werkzeug=2.0.2=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.2=py39hf3d152e_1
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h4bd325d_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h7f98852_0
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yaml-cpp=0.6.3=he1b5a44_4
  - yarl=1.7.2=py39h3811e60_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zfp=0.5.5=h9c3ff4c_8
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - pip:
    - dv==1.0.10
    - ffmpeg-python==0.2.0
    - flatbuffers==2.0
    - future==0.18.2
    - greenlet==1.1.2
    - lz4==4.0.0
    - msgpack==1.0.3
    - orderedattrdict==1.6.0
    - panwid==0.3.5
    - pycollada==0.7.2
    - pyglm==2.5.7
    - pymarchingcubes==0.0.2
    - pymcubes==0.1.2
    - pynvim==0.4.3
    - pytorch-ranger==0.1.1
    - raccoon==3.0.0
    - ranger-fm==1.9.3
    - tabulate==0.8.9
    - torch-optimizer==0.3.0
    - urwid==2.1.2
    - urwid-readline==0.13
    - urwid-utils==0.1.3.dev0
    - zstd==1.5.2.5
